In [8]:
import random as rd
import numpy as np

x1 = y1 = x2 = y2 = x3 = y3 = x4 = y4 = sh1 = sh2 = 6

class player:
    def __init__(self, posicion, tamaño, orientacion, shot=[0,0]):
        self.posicion = posicion
        self.tamaño = tamaño
        self.orientacion = orientacion
        self.shot = shot

class jugador(player):
    def __init__(self, posicion, tamaño, orientacion, shot=[0,0]):
        super().__init__(posicion, tamaño, orientacion, shot=[0,0])
    def shoter(self, Mshot):
        self.shot = Mshot

class COM(player):
    def __init__(self, posicion, tamaño, orientacion, shot=[0,0]):
        super().__init__(posicion, tamaño, orientacion, shot=[0,0])
    def shoter(self, Mshot):
        self.shot = Mshot

class Tablero_de_juego:
    def __init__(self):
        self.tablero_jugador = np.zeros((6,6))
        self.tablero_COM = np.zeros((6,6))
        self.available = True
    def add_boat_jugador(self, jugador):
        if jugador.orientacion == "H":
            for i in range(jugador.tamaño):
                self.tablero_jugador[jugador.posicion[0]][jugador.posicion[1]+i] = 1
        else:
            for i in range(jugador.tamaño):
                self.tablero_jugador[jugador.posicion[0]+i][jugador.posicion[1]] = 1
        print("Bote agregado en Jugador")
        print("La matriz queda: ")
        print(self.tablero_jugador)
    def add_boat_com(self, COM):
        if COM.orientacion == "H":
            for i in range(COM.tamaño):
                self.tablero_COM[COM.posicion[0]][COM.posicion[1]+i] = 1
        else:
            for i in range(COM.tamaño):
                self.tablero_COM[COM.posicion[0]+i][COM.posicion[1]] = 1
        print("Bote agregado en COM")
        print("La matriz queda: ")
        print(self.tablero_COM)
    def check_crash_jugador(self, jugador):
        if self.tablero_COM[jugador.shot[0]][jugador.shot[1]] == 1:
            self.tablero_COM[jugador.shot[0]][jugador.shot[1]] = 0
            print("Impacto")
            print("La matriz queda: ")
            print(self.tablero_COM)
        else:
            print("Agua")
    def check_crash_com(self, COM):
        if self.tablero_jugador[COM.shot[0]][COM.shot[1]] == 1:
            self.tablero_jugador[COM.shot[0]][COM.shot[1]] = 0
            print("Impacto")
            print("La matriz queda: ")
            print(self.tablero_jugador)
        else:
            print("Agua")
    def winner(self):
        if np.sum(self.tablero_jugador) == 0:
            self.available = False
            print("Ganó COM")
            
        if np.sum(self.tablero_COM) == 0:
            self.available = False
            print("Ganó jugador")
            

#Creacion de Tablero
Board = Tablero_de_juego()

#Creacion de Botes para COM (4 botes)
COM1 = COM([rd.randint(0,5),rd.randint(0,3)],3,"H")
COM2 = COM([rd.randint(0,5),rd.randint(0,4)],2,"H")
COM3 = COM([rd.randint(0,3),rd.randint(0,5)],3,"V")
COM4 = COM([rd.randint(0,2),rd.randint(0,5)],4,"V")

#Asignacion de botes para COM
Board.add_boat_com(COM1)
Board.add_boat_com(COM2)
Board.add_boat_com(COM3)
Board.add_boat_com(COM4)

print("GUERRA NAVAL")
print("Tu oponente ya tiene sus barcos en posicion, ahora ubica los tuyos")
while y1 > 3 and y2 > 4 and x3 > 3 and x4 > 2:
    print("Recuerda que no podras poner ubicaciones mayores a 5")
    print("Este es un barco horizontal")
    x1 = int(input("Ingrese fila para un barco tamaño 3: "))
    y1 = int(input("Ingrese columna (Entre 0 a 3) para un barco tamaño 3: "))
    if x1 < 6 and x1 > -1 and y1 < 4 and y1 > -1:
        pos1 = jugador([x1,y1],3,"H")
        Board.add_boat_jugador(pos1)

    print("Este es un barco horizontal")
    x2 = int(input("Ingrese fila para un barco tamaño 2: "))
    y2 = int(input("Ingrese columna (Entre 0 a 4) para un barco tamaño 2: "))
    if x2 < 6 and x2 > -1 and y2 < 5 and y2 > -1:
        pos2 = jugador([x2,y2],2,"H")
        Board.add_boat_jugador(pos2)

    print("Este es un barco vertical")
    x3 = int(input("Ingrese fila (Entre 0 a 3) para un barco tamaño 3: "))
    y3 = int(input("Ingrese columna para un barco tamaño 3: "))
    if x3 < 4 and x3 > -1 and y3 < 6 and y3 > -1:
        pos3 = jugador([x3,y3],3,"V")
        Board.add_boat_jugador(pos3)
    
    print("Este es un barco vertical")
    x4 = int(input("Ingrese fila (Entre 0 a 2) para un barco tamaño 4: "))
    y4 = int(input("Ingrese columna para un barco tamaño 4: "))
    if x4 < 3 and x4 > -1 and y4 < 6 and y4 > -1:
        pos4 = jugador([x4,y4],4,"V")
        Board.add_boat_jugador(pos4)
    

print("Inicia el juego")
while Board.available:
    print("Recuerda que no podras poner filas o columnas mayores a 5")
    while sh1 < 0 or sh1 > 5 and sh2 < 0 or sh2 > 5:
        sh1 = int(input("Ingresa fila (entre 0 a 5) para tu disparo a tu oponente: "))
        sh2 = int(input("Ingresa columna (entre 0 a 5) para tu disparo a tu oponente: "))
    pos1.shoter([sh1,sh2])
    Board.check_crash_jugador(pos1)
    #Ahora dispara la maquina
    COM1.shoter([rd.randint(0,5),rd.randint(0,5)])
    Board.check_crash_com(COM1)
    #Se verifica si alguien gana
    Board.winner()
    sh1 = 6
    sh2 = 6
print("Fin del juego")


Bote agregado en COM
La matriz queda: 
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
Bote agregado en COM
La matriz queda: 
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0.]]
Bote agregado en COM
La matriz queda: 
[[0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0.]]
Bote agregado en COM
La matriz queda: 
[[0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0. 0.]
 [0. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0.]]
GUERRA NAVAL
Tu oponente ya tiene sus barcos en posicion, ahora ubica los tuyos
Recuerda que no podras poner ubicaciones mayores a 5
Este es un barco horizontal


Ingrese fila para un barco tamaño 3:  2
Ingrese columna (Entre 0 a 3) para un barco tamaño 3:  0


Bote agregado en Jugador
La matriz queda: 
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
Este es un barco horizontal


Ingrese fila para un barco tamaño 2:  5
Ingrese columna (Entre 0 a 4) para un barco tamaño 2:  0


Bote agregado en Jugador
La matriz queda: 
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0.]]
Este es un barco vertical


Ingrese fila (Entre 0 a 3) para un barco tamaño 3:  0
Ingrese columna para un barco tamaño 3:  0


Bote agregado en Jugador
La matriz queda: 
[[1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0.]]
Este es un barco vertical


Ingrese fila (Entre 0 a 2) para un barco tamaño 4:  0
Ingrese columna para un barco tamaño 4:  2


Bote agregado en Jugador
La matriz queda: 
[[1. 0. 1. 0. 0. 0.]
 [1. 0. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0.]]
Inicia el juego
Recuerda que no podras poner filas o columnas mayores a 5


Ingresa fila (entre 0 a 5) para tu disparo a tu oponente:  1
Ingresa columna (entre 0 a 5) para tu disparo a tu oponente:  1


Impacto
La matriz queda: 
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0. 0.]
 [0. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0.]]
Impacto
La matriz queda: 
[[1. 0. 1. 0. 0. 0.]
 [1. 0. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0.]]
Recuerda que no podras poner filas o columnas mayores a 5


Ingresa fila (entre 0 a 5) para tu disparo a tu oponente:  2
Ingresa columna (entre 0 a 5) para tu disparo a tu oponente:  1


Impacto
La matriz queda: 
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0.]]
Impacto
La matriz queda: 
[[1. 0. 1. 0. 0. 0.]
 [1. 0. 1. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0.]]
Recuerda que no podras poner filas o columnas mayores a 5


Ingresa fila (entre 0 a 5) para tu disparo a tu oponente:  3
Ingresa columna (entre 0 a 5) para tu disparo a tu oponente:  1


Impacto
La matriz queda: 
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0.]]
Agua
Recuerda que no podras poner filas o columnas mayores a 5


Ingresa fila (entre 0 a 5) para tu disparo a tu oponente:  4
Ingresa columna (entre 0 a 5) para tu disparo a tu oponente:  1


Impacto
La matriz queda: 
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [1. 0. 1. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0.]]
Agua
Recuerda que no podras poner filas o columnas mayores a 5


Ingresa fila (entre 0 a 5) para tu disparo a tu oponente:  4
Ingresa columna (entre 0 a 5) para tu disparo a tu oponente:  0


Impacto
La matriz queda: 
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0.]]
Agua
Recuerda que no podras poner filas o columnas mayores a 5


Ingresa fila (entre 0 a 5) para tu disparo a tu oponente:  2
Ingresa columna (entre 0 a 5) para tu disparo a tu oponente:  2


Impacto
La matriz queda: 
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0.]]
Impacto
La matriz queda: 
[[1. 0. 1. 0. 0. 0.]
 [1. 0. 1. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]]
Recuerda que no podras poner filas o columnas mayores a 5


Ingresa fila (entre 0 a 5) para tu disparo a tu oponente:  3
Ingresa columna (entre 0 a 5) para tu disparo a tu oponente:  2


Impacto
La matriz queda: 
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0.]]
Impacto
La matriz queda: 
[[0. 0. 1. 0. 0. 0.]
 [1. 0. 1. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]]
Recuerda que no podras poner filas o columnas mayores a 5


Ingresa fila (entre 0 a 5) para tu disparo a tu oponente:  4
Ingresa columna (entre 0 a 5) para tu disparo a tu oponente:  2


Impacto
La matriz queda: 
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0.]]
Agua
Recuerda que no podras poner filas o columnas mayores a 5


Ingresa fila (entre 0 a 5) para tu disparo a tu oponente:  5
Ingresa columna (entre 0 a 5) para tu disparo a tu oponente:  2


Impacto
La matriz queda: 
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]]
Agua
Recuerda que no podras poner filas o columnas mayores a 5


Ingresa fila (entre 0 a 5) para tu disparo a tu oponente:  5
Ingresa columna (entre 0 a 5) para tu disparo a tu oponente:  3


Impacto
La matriz queda: 
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
Agua
Ganó jugador
Fin del juego
